title: Tomb Raider Archives
description: A comprehensive archive of the Tomb Raider franchise — games, movies, and series.
url: "https://tombraiderarchives.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - package.json
